# This file contains configuration of the build. It may be generated by some
# script in the future.

# The RELATIVE variable is for the wrapper makefiles.
O := $(RELATIVE).
S := $(RELATIVE).
ASCIIDOC := asciidoc
AR := ar
PAGE_SIZE := $(shell getconf PAGE_SIZE)

ifeq ($(USE_LAYER),USE_LAYER_I2C)
INST_SPECIAL := bin/atsha204cmd bin/chiptools bin/chipinit bin/chiptest
else
INST_SPECIAL := bin/atsha204cmd
endif

include $(S)/Makefile.dir

.PHONY: install

install:
	cp src/libatsha204/atsha204.h /usr/include/
	cp lib/libatsha204.so /usr/lib
	cp $(INST_SPECIAL) /usr/bin
	$(if $(PYTHON), cp lib/atsha204.so /usr/lib/python$(PYTHON_VERSION)/dist-packages)
	ldconfig
