# This file contains configuration of the build. It may be generated by some
# script in the future.

# The RELATIVE variable is for the wrapper makefiles.
O := $(RELATIVE).
S := $(RELATIVE).
ASCIIDOC := asciidoc
AR := ar
PAGE_SIZE := $(shell getconf PAGE_SIZE)

include $(S)/Makefile.dir

.PHONY: install

install:
	cp src/libatsha204/atsha204.h /usr/include/
	cp lib/libatsha204.so /usr/lib
	cp bin/toolbox /usr/bin
	cp bin/atsha204cmd /usr/bin
	cp bin/chipinit /usr/bin
	cp bin/chiptest /usr/bin
	ldconfig
