BINARIES += src/chiplib

chiplib_MODULES := main \
	emulation \
	communication \
	tools \
	layer_usb \
	error

#nuci_PKG_CONFIGS := $(LUA_NAME) libnetconf
#nuci_EXE_CONFIGS := xml2
#nuci_LOCAL_LIBS := xmlwrap
#nuci_SYSTEM_LIBS := uci

#DOCS += src/plugins

#include $(S)/src/lua_plugins/Makefile.dir
