include $(S)/src/libatsha204/Makefile.dir
include $(S)/src/dev/Makefile.dir
include $(S)/src/hmactest/Makefile.dir
include $(S)/src/ucollect_example/Makefile.dir
include $(S)/src/atsha204cmd/Makefile.dir
