BINARIES += src/ucollect_example/ucollect_example

ucollect_example_MODULES := main
ucollect_example_LOCAL_LIBS := atsha204

ucollect_example_SYSTEM_LIBS := crypto unbound ftdi
#DOCS += src/ucollect/ucollect
